= NGINX

[#descripcion]
== Descripción

NGINX es un  un servidor HTTP/proxy inverso, un servidor proxy de correo y un servidor proxy TCP/UDP genérico.

Para obtener más información, consulte la documentación oficial de https://nginx.org/en/docs/[NGINX].


[#instalacion]
== Instalación

Para obtener una guía detallada de la instalación de NGINX, consulte la sección https://nginx.org/en/docs/install.html[Installing nginx] de la documentación oficial de NGINX. De forma alternativa puede utilizar un https://hub.docker.com/_/nginx[contenedor de Docker].


[#archivos_configuración]
== Archivos de configuración

El comportamiento de NGINX y sus módulos es descrito en sus archivos de configuración. El archivo de configuración principal de NGINX, llamado _nginx.conf_, se ubica en el directorio _/etc/nginx_:

./etc/nginx/nginx.conf
----
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
----

El resto de archivos de configuración de NGINX se encuentran en el directorio _/etc/nginx/conf.d/_. Por defecto, en este directorio solo existe el archivo _default.conf_:

.default.conf
----
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
----

[IMPORTANT, caption=IMPORTANTE]
====
Todas las configuraciones mostradas en las siguientes secciones deben realizarse en el archivo _default.conf_, a menos que se indique lo contrario.
====


[#reverse_proxy]
== Reverse Proxy

Configuración de NGINX como un proxy inverso para HTTP.

Para obtener más información, consulta la sección https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/[NGINX Reverse Proxy] de la documentación oficial de NGINX.


[#request_to_proxied_server]
=== Passing a Request to a Proxied Server

Para pasar una solicitud a un servidor proxy HTTP, la directiva `proxy_pass` se especifica dentro de una ubicación (_location_). Por ejemplo:
----
    location /some/path/ {
        proxy_pass http://www.example.com/;
    }
----

Esta configuración de ejemplo pasa todas las solicitudes procesadas en la ubicación `/some/path/` al servidor proxy de la dirección `http://www.example.com/`. Esta dirección se puede especificar como un nombre de dominio o una dirección IP. La dirección también puede incluir un puerto:
----
    location / {
        proxy_pass http://148.206.50.80:3035/;
    }
----


[#request_headers]
=== Passing Request Headers

De forma predeterminada, NGINX redefine el campo de encabezado `Host` utilizando la variable `$proxy_host`. Para cambiar esta configuración, así como modificar otros campos de encabezado, usa la directiva `proxy_set_header`. Por ejemplo:
----
    location /kb/ {
       proxy_pass http://148.206.50.80:3036/;
       proxy_set_header Host $http_host/kb;
       proxy_set_header X-Real-IP $remote_addr;
    }
----

Para obtener más información de la directiva `proxy_set_header`, consulta la sección https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header[proxy_set_header] de la documentación oficial de NGINX.


[#upstream]
== Upstream

La directiva `upstream` permite definir grupos de servidores. Esta directiva debe colocarse dentro de un bloque `http`.

Los servidores de un grupo son configurados utilizando la directiva `server`. Por ejemplo, la siguiente configuración define un grupo llamado `supercomputo` con un servidor:

----
upstream supercomputo {
    server 148.206.50.80:3035;
}
----

Para pasar solicitudes a un grupo de servidores, el nombre del grupo debe ser especificado en la directiva `proxy_pass`:

----
    location / {
        proxy_pass http://supercomputo/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
----

Para obtener más información, consulta la sección https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#proxying-http-traffic-to-a-group-of-servers[Proxying HTTP Traffic to a Group of Servers] de la documentación oficial de NGINX.


[#https]
== HTTPS

[#certificados_ssl]
=== Certificados SSL

Para configurar un servidor HTTPS, verifica que el servidor está escuchando en el puerto 443, e incluya el parámetro `ssl` en directiva `listen`:
----
server {
    listen      443 ssl;
    server_name supercomputo.izt.uam.mx;

    ...
}
----

Después especifica las ubicaciones del certificado del servidor y los archivos de clave privada:
----
server {
    listen      443 ssl;
    server_name supercomputo.izt.uam.mx;

    ssl_certificate /etc/nginx/ssl/live/supercomputo.izt.uam.mx/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl//live/supercomputo.izt.uam.mx/privkey.pem;

    ...
}
----

Para obtener más información, consulta la sección https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/#setting-up-an-https-server[Setting up an HTTPS Server] de la documentación oficial de NGINX.


[#http_to_https]
=== HTTP to HTTPS Redirect

Para redirigir el tráfico HTTP a HTTPS, cree un nuevo bloque `server`, y agregue la siguiente información:

----
server {
   listen 80;
   server_name supercomputo.izt.uam.mx;

   return 301 https://$host$request_uri;
}
----

Para obtener más información, consulta el siguiente https://linuxhint.com/nginx-redirect-http-https/[sitio].
