services:
  mdbook:
    container_name: Yoltla_Kb_Mdbook
    # image: peaceiris/mdbook:latest
    # image: peaceiris/mdbook:v0.4.40
    build: .
    stdin_open: true
    tty: true
    ports:
      - 4000:3000
      - 3001:3001
    volumes:
      - ${PWD}:/book
    command:
      - serve
      - --hostname
      - '0.0.0.0'
