[#osu]
= OSU Micro-Benchmarks

[#descripcion]
== Descripción

El conjunto http://mvapich.cse.ohio-state.edu/benchmarks/[OSU Micro-Benchmarks] presentan una serie de benchmarks de `MPI` que miden el rendimiento de varias operaciones de MPI:

* Point-to-Point MPI Benchmarks: Este Benchmarks mide la latencia, latencia de subprocesos múltiples, latencia de pares múltiples, ancho de banda múltiple / ancho de banda de prueba de velocidad de mensajes, ancho de banda bidireccional.

* Collective MPI Benchmarks: Este Benchmarks mide pruebas de latencia colectiva para varias operaciones colectivas de MPI, como MPI_Allgather, MPI_Alltoall, MPI_Allreduce, MPI_Barrier, MPI_Bcast, MPI_Gather, MPI_Reduce, MPI_Reduce_Scatter, MPI_Scatter y colectivos vectoriales.

* One-sided MPI Benchmarks: Este Benchmarks mide la latencia unilateral, ancho de banda unilateral, latencia unilateral, latencia de acumulación unilateral, etc.


[referencias]
== Referencias

* http://mvapich.cse.ohio-state.edu/benchmarks/[OSU micro-benchmarks]
* https://ulhpc-tutorials.readthedocs.io/en/latest/parallel/mpi/OSU_MicroBenchmarks/[Tutorial: Building and Runnning OSU Micro-Benchmarks]